 export const APPURLs = {
  base:'https://localhost:7161/api/',
  login: 'User/signin',
  register: 'User/submmitresume',
  usercheck:'register/checkuser',
  changePassword:'user/passwordreset',
  dashboardStateOption:'dashboard/states',
  dashboardProgrammeOption:'dashboard/programmes',
  dashboardCountLocation:'dashboard/batches',
  agencylist:'agency/list',
  agencyexport:'exporttoexcel/user',
  agencynewexport:'exporttoexcel/agencies',
  programmeexport:'exporttoexcel/programmes',
  vewreportexport:'exporttoexcel/viewreportexcel',
  summaryexport:'exporttoexcel/summary',
  activeagencylist:'agency/activeagencies',
  agencydetail:'agency/detail',
  agencypost:'agency/add',
  agencyedit:'agency/edit',
  agencystatus:'agency/auditorstatus',
  qcapprovallist:'agency/qcapproval',
  viewReportlist:'viewreport/report',
  qcstatuschangetoAprove:'agency/qcapproveprogramme',
  qcstatuschangetoReject:'agency/qcrejectprogramme',
  qcprogrammeapprove:'programme/approve',
  statesall:'common/states',
  districtbystates:'common/statedistricts',
  programmelist:'programme/list',
  trainingprogrammelist:'batchenroll/programmes',
  trainingprogrammeenroll:'batchenroll/enroll',
  programmenewlist:'programme/newlist',
  programmeprogrammes:'programme/tprogrammes',
  programmecoordinators:'programme/coordinators',
  programmeleadTrainers:'programme/leadtrainers',
  programmeorganisingParter:'programme/organisingpartners',
  newProgrameePost:'programme/add',
  batchdetailVenue:'batchdetail/venue',
  batchdetailMonitoring:'batchdetail/monitoring',
  batchdetailTrainers:'batchdetail/trainers',
  batchdetailFeedback:'batchdetail/feedbacks',
  batchdetailAttendance:'batchdetail/attendance',
  organisingpartner:'organisingpartner/list',
  organisingpartnerPOST:'organisingpartner/add',
  curriculumlist:'curriculum/list',
  curriculumstatuschange:'curriculum/changestatus',
  curriculumnpost:"curriculum/add",
  curriculumnupdate:"curriculum/update",
  sessionlist:"curriculum/sessions",
  sessionPost:"curriculum/addsession",
  sessionEdit:"curriculum/editsession",
  topiclist:"curriculum/topics",
  topicEdit:"curriculum/edittopic",
  topicAdd:"curriculum/addtopic",
  programmesummarylist:'summaryreport/summary',
  reportcurriculum:"summaryreport/curiculumbind",
  trainerlist:'trainer/list',
  facultylist:'trainer/facultylist',
  trainerstatus:'trainer/status',
  trainerpost:'trainer/addtrainer',
  trainerallotment:'trainer/agencylist',
  trainerassignment:'trainer/allocatefaculty',
  trainerunassignment:'trainer/unallocatefaculty',
  trainerdetail:'trainer/detail',
  registrationlist:'mtatct/list',
  registrationlistias:'mtatct/listias',
  registrationstatuschange:'mtatct/statusChange',
  registrationdetail:'mtatct/detail',
  certificateslist:'certificate/list',
  participantslist:'certificate/programmeparticipants',
  certificatedetail:'certificate/getCertificate',
  participantUploadBatches:'participant/uploadbatches',
  participantUpload:'participant/upload',
  orgcategorylist:'orgcategory',
  orgcategoryadd:'orgcategory',
  orgcategorystatus:'orgcategory',
  orgsubcategoryadd:'orgcategory',
  categoryadminlist:'categoryadmin',
  categoryadminadd:'categoryadmin',
  categoryadminstatus:'categoryadmin',
  participantRegister:'participant/register',
  participantSignin:'participant/signin',
  participantVerifyEmail:'participant/verifyemail',
  participantMyProgrammes:'participant/myprogrammes',
  participantCategories:'participant/categories',
  participantGetCandidates:'participant/candidates',
  assessmentCheckStatus: 'assessment/checkexamstatus',
  assessmentQuestions: 'assessment/questions',
  assessmentSubmitQuestions: 'assessment/submitquestions',
  assessmentFinalSubmit: 'assessment/finalsubmit',
  assessmentUploadImage: 'assessment/uploadimage',
  assessmentUploadBase64Image: 'assessment/uploadbase64image',
  questionnaireGet: 'questionnaire/get',
  questionnaireUpdate: 'questionnaire/update',
  questionnaireAddQuestion: 'questionnaire/addquestion',
  trainingCheckExamEnabled: 'training/checkexamenabled',
  trainingStartExam: 'training/startexam',
  trainingSubmitPrecourseExam: 'training/submitprecourseexam',
  trainingSubmitFinalExam: 'training/submitfinalexam',
  trainingSubmitFeedback: 'training/submitfeedback',
  trainingSubmitVideo: 'training/submitvideo',
  trainingSubmitPScore: 'training/submitpscore',
  trainingSubmitMScore: 'training/submitmscore',
  trainingUpdateExamTime: 'training/updateexamtime',
  trainingUpdateExamStartEndTime: 'training/updateexamstartendtime',
  trainingBatchRegistrations: 'training/batchregistrations',
  trainingForwardToZed: 'training/forwardtozed',
  trainingUpdateRegistrationDetails: 'training/updateregistrationdetails',
}