import { environment } from '../../../environments/environment';
export const API_STATIC_BASE = environment.staticBase;

export const APPURLs = {
  base:'https://localhost:7161/api/',
  login: 'User/signin',
  register: 'User/submmitresume',
  usercheck:'register/checkuser',
  changePassword:'user/passwordreset',
  dashboardStateOption:'dashboard/states',
  dashboardProgrammeOption:'dashboard/programmes',
  dashboardCountLocation:'dashboard/batches',
  agencylist:'agency/list',
  coordinatorlist:'agency/coordinators',
  agencyexport:'exporttoexcel/user',
  coordinatorexport:'exporttoexcel/coordinators',
  agencynewexport:'exporttoexcel/agencies',
  programmeexport:'exporttoexcel/programmes',
  vewreportexport:'exporttoexcel/viewreportexcel',
  summaryexport:'exporttoexcel/summary',
  activeagencylist:'agency/activeagencies',
  agencydetail:'agency/detail',
  agencypost:'agency/add',
  coordinatorpost:'coordinator/add',
  agencyedit:'agency/edit',
  agencystatus:'agency/auditorstatus',
  qcapprovallist:'agency/qcapproval',
  viewReportlist:'viewreport/report',
  qcstatuschangetoAprove:'agency/qcapproveprogramme',
  qcstatuschangetoReject:'agency/qcrejectprogramme',
  qcprogrammeapprove:'programme/approve',
  programmereject:'programme/reject',
  programmeCloseRegistration:'programme/closeregistration',
  programmeOpenRegistration:'programme/openregistration',
  programmePostpone:'programme/postpone',
  programmeCreateCalendar:'programme/createcalendar',
  statesall:'common/states',
  districtbystates:'common/statedistricts',
  programmelist:'programme/list',
  trainingprogrammelist:'batchenroll/programmes',
  trainingprogrammeenroll:'batchenroll/enroll',
  programmenewlist:'programme/newlist',
  programmeprogrammes:'programme/tprogrammes',
  programmecoordinators:'programme/coordinators',
  programmeleadTrainers:'programme/leadtrainers',
  programmeorganisingParter:'programme/organisingpartners',
  newProgrameePost:'programme/add',
  batchdetailVenue:'batchdetail/venue',
  batchdetailMonitoring:'batchdetail/monitoring',
  batchdetailTrainers:'batchdetail/trainers',
  batchdetailFeedback:'batchdetail/feedback',
  batchdetailAttendance:'batchdetail/attendance',
  batchdetailAttendancePhotos:'batchdetail/attendancephotos',
  batchdetailFeedbackPhotos:'batchdetail/feedbackphotos',
  batchdetailParticipants:'batchdetail/participants',
  organisingpartner:'organisingpartner/list',
  organisingpartnerPOST:'organisingpartner/add',
  curriculumlist:'curriculum/list',
  curriculumstatuschange:'curriculum/changestatus',
  curriculumnpost:"curriculum/add",
  curriculumnupdate:"curriculum/update",
  sessionlist:"curriculum/sessions",
  sessionPost:"curriculum/addsession",
  sessionEdit:"curriculum/editsession",
  topiclist:"curriculum/topics",
  topicEdit:"curriculum/edittopic",
  topicAdd:"curriculum/addtopic",
  programmesummarylist:'summaryreport/summary',
  reportcurriculum:"summaryreport/curiculumbind",
  trainerlist:'trainer/list',
  facultylist:'trainer/facultylist',
  trainerstatus:'trainer/status',
  trainerpost:'trainer/addtrainer',
  trainerallotment:'trainer/agencylist',
  trainerassignment:'trainer/allocatefaculty',
  trainerunassignment:'trainer/unallocatefaculty',
  trainerdetail:'trainer/detail',
  registrationlist:'mtatct/list',
  registrationexport:'mtatct/export',
  registrationlistias:'mtatct/listias',
  registrationstatuschange:'mtatct/statusChange',
  registrationdetail:'mtatct/detail',
  certificateslist:'certificate/list',
  participantslist:'certificate/programmeparticipants',
  certificatedetail:'certificate/getCertificate',
  certificateGenerate:'certificate/generate',
  certificateDownload:'certificate/download',
  certificateVerify:'certificate/verify',
  participantUploadBatches:'participant/uploadbatches',
  participantUpload:'participant/upload',
  orgcategorylist:'orgcategory',
  orgcategoryadd:'orgcategory',
  orgcategorystatus:'orgcategory',
  orgsubcategoryadd:'orgcategory',
  categoryadminlist:'categoryadmin',
  categoryadminadd:'categoryadmin',
  categoryadminstatus:'categoryadmin',
  participantRegister:'participant/register',
  participantVerifyOtp:'participant/verifyotp',
  participantSignin:'participant/signin',
  participantVerifyEmail:'participant/verifyemail',
  participantMyProgrammes:'participant/myprogrammes',
  participantCategories:'participant/categories',
  participantGetCandidates:'participant/candidates',
  participantForgotPassword:'participant/forgotpassword',
  participantVerifyResetOtp:'participant/verifyresetotp',
  userForgotPassword:'user/forgotpassword',
  userVerifyResetOtp:'user/verifyresetotp',
  participantChangePassword:'participant/changepassword',
  participantProfile:'participant/profile',
  participantApplicationStatus:'participant/applicationstatus',
  participantMyApplication:'participant/myapplication',
  participantOngoingProgrammes:'participant/ongoingprogrammes',
  participantEnroll:'participant/enroll',
  assessmentCheckStatus: 'assessment/checkexamstatus',
  assessmentQuestions: 'assessment/questions',
  assessmentSubmitQuestions: 'assessment/submitquestions',
  assessmentFinalSubmit: 'assessment/finalsubmit',
  assessmentUploadImage: 'assessment/uploadimage',
  assessmentUploadBase64Image: 'assessment/uploadbase64image',
  questionnaireGet: 'questionnaire/get',
  questionnaireUpdate: 'questionnaire/update',
  questionnaireAddQuestion: 'questionnaire/addquestion',
  trainingCheckExamEnabled: 'training/checkexamenabled',
  trainingStartExam: 'training/startexam',
  trainingSubmitPrecourseExam: 'training/submitprecourseexam',
  trainingSubmitFinalExam: 'training/submitfinalexam',
  trainingSubmitFeedback: 'training/submitfeedback',
  trainingSubmitVideo: 'training/submitvideo',
  trainingSubmitPScore: 'training/submitpscore',
  trainingSubmitMScore: 'training/submitmscore',
  trainingUpdateExamTime: 'training/updateexamtime',
  trainingUpdateExamStartEndTime: 'training/updateexamstartendtime',
  trainingBatchRegistrations: 'training/batchregistrations',
  trainingForwardToZed: 'training/forwardtozed',
  trainingUpdateRegistrationDetails: 'training/updateregistrationdetails',
  registrationSteps: 'registrationstepconfig',
  registrationStepsAdmin: 'registrationstepconfig/admin',
  registrationStepsToggle: 'registrationstepconfig/toggle',
  practicalScoresBatches: 'practicalscores/batches',
  practicalScoresGet: 'practicalscores/scores',
  practicalScoresSubmit: 'practicalscores/submitscores',
  questionBankSummary: 'masterquestionbank/summary',
  questionBankList: 'masterquestionbank/questions',
  questionBankAdd: 'masterquestionbank/add',
  questionBankUpdate: 'masterquestionbank',
  questionBankDelete: 'masterquestionbank',
  documentUpload: 'documentupload/upload',
  documentList: 'documentupload/list',
  documentDelete: 'documentupload',
  documentUpdate: 'documentupload',
  dashboardCategoryAdminStats: 'dashboard/categoryadmin',
  dashboardCategoryAdminStates: 'dashboard/categoryadminstates',
  applicationStart: 'application/start',
  applicationProgress: 'application/progress',
  applicationSubmit: 'application/submit',
  applicationStepPhoto: 'application/photo',
  applicationStepIdProof: 'application/idproof',
  applicationStepNomination: 'application/nomination',
  applicationStepPersonal: 'application/personal',
  applicationStepAddress: 'application/address',
  applicationStepLanguages: 'application/languages',
  applicationStepQualifications: 'application/qualifications',
  applicationStepExperience: 'application/experience',
  applicationStepIndustryExperience: 'application/industryexperience',
  applicationStepSkills: 'application/skills',
  applicationStepRoleExperience: 'application/roleexperience',
  applicationStepDeclaration: 'application/declaration',
  participantMyCertificates: 'participant/mycertificates',
}